name: CD

on:
  push:
    branches: [ main ]

  schedule:
  # build once every day at 1am
  - cron: "0 1 * * *"

  # allow manually trigger a build
  workflow_dispatch:

jobs:
  CD:

    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        # Number of commits to fetch. 0 indicates all history for all branches and tags.
        # Default: 1
        # Only keep the latest 10 history to limit repo size
        fetch-depth: 0              # otherwise, you will failed to push refs to dest repo

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        # architecture: x64

    - name: Check build env
      run: |
        echo "pwd: $(pwd)"
        echo "USER: $USER"
        echo "HOME: $HOME"
        echo "SHELL: $SHELL"
        echo "PATH: $PATH"
        python3 --version
        pip3 --version
        ulimit -a

    - name: Setup
      run: |
        # pip install binary to $HOME/.local/bin
        # export PATH="$PATH:$HOME/.local/bin"
        #
        # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
        echo "/home/runner/.local/bin" >> $GITHUB_PATH
        pip3 install -r requirements.txt

    - name: Build
      run: |
        ./main.sh

    - name: Check changes and clean cache
      run: |
        gzip --best *.txt *.db *.log
        ls -lh
        git status

    - name: Git config
      run: |
        git config --local user.email "CD@github-action"
        git config --local user.name "GitHub Action"

    - name: Commit changes on release branch
      run: |
        git checkout --orphan release

        git add *.gz
        git commit -m "Update data files" *.gz

    - name: Force push data branch changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # branch: ${{ github.ref }}
        branch: release
        force: true
